# Site settings
title: Huong Pham
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Huong Pham
user_description: Life's a rollercoaster, and if you're not screaming with joy, you're missing out on the ride!
user_title: Computer Vision / Deep Learning Scientist
email: huong.n.pham01@gmail.com
twitter_username: hpham
github_username:  hogmeade
gplus_username:  hpham

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
